name: DemoServerSim
options:
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  DemoServerSim:
    type: application
    platform: iOS
    sources:
      - path: DemoServerSim
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iosdailydemo.DemoServerSim
        INFOPLIST_FILE: DemoServerSim/Info.plist
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
