# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'TestEpoxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # pod 'EpoxyCore'
  # pod 'EpoxyLayoutGroups'

  pod 'Epoxy'


  # Pods for TestEpoxy

end
