name: DemoTableViewDiffable
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  DemoTableViewDiffable:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: DemoTableViewDiffable
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.demotableviewdiffable
        INFOPLIST_FILE: DemoTableViewDiffable/Info.plist
