# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestOpenCombine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'OpenCombine', '~> 0.12.0'
	pod 'OpenCombineDispatch', '~> 0.12.0'
	pod 'OpenCombineFoundation', '~> 0.12.0'
  # Pods for TestOpenCombine

end
