# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# pod


# demo

target 'TestEpoxySourceCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  require '/Users/dinglan/Downloads/demo/open_source/epoxy-ios/custom_run.rb'

  custom_run


end